version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_DATABASE=qbuild
      - MYSQL_ROOT_PASSWORD=/run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - ./data:/var/lib/mysql
  
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on: 
      - backend
volumes:
  data: 

secrets:
  db-password:
    file: ./db-password.txt